version: '3.9'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse_sipstr
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host=localhost", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

  postgres:
    image: postgis/postgis:17-3.4
    container_name: postgres
    environment:
      POSTGRES_USER: sipstr_rw_user
      POSTGRES_PASSWORD: sipstr_rw_user
      POSTGRES_DB: sipstr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sipstr_rw_user"]
      interval: 10s
      retries: 5
      start_period: 30s

  signoz-query-service:
    image: signoz/query-service:0.43.1
    container_name: signoz-query-service
    environment:
      - PREFER_DB=postgres
      - USER_MANAGEMENT_DATABASE=postgres
      - POSTGRES_URI=postgres://sipstr_rw_user:sipstr_rw_user@postgres:5432/sipstr
      - STORAGE=clickhouse
      - ClickHouseUrl=tcp://clickhouse_sipstr:9000?username=default
      - CLICKHOUSE_TRACE_DATABASE=signoz_traces
      - CLICKHOUSE_LOGS_DATABASE=signoz_logs_db
      - CLICKHOUSE_METRICS_DATABASE=signoz_metrics
      - SIGNOZ_JWT_SECRET=supersecurejwtsecret
      - USER_AUTH_ENABLED=true
    volumes:
      - query-service-data:/var/lib/signoz
    ports:
      - "8080:8080"
      - "8085:8085"
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

  otel_collector_sipstr:
    image: signoz/signoz-otel-collector:0.88.3
    container_name: otel_collector_sipstr
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml:ro
    command: [ "--config=/etc/otel/config.yaml" ]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
    depends_on:
      clickhouse:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:13133"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

  signoz-frontend:
    image: signoz/frontend:0.43.1
    container_name: signoz-frontend
    ports:
      - "3301:3301"
    environment:
      FRONTEND_API_ENDPOINT: http://localhost:8080
    volumes:
      - /c/sipstrlogdemo/frontend-env.js:/usr/share/nginx/html/config/env.js
    depends_on:
      signoz-query-service:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      otel_collector_sipstr:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend

volumes:
  clickhouse-data:
  postgres_data:
  query-service-data:

networks:
  backend:
